galaxy_info:
  author: Arslan Kareem
  description: Assignment 07 nginx configuration
  license: MIT
  min_ansible_version: "2.21"
  galaxy_tags:
    - assignment7
    - devops
    - nginx

dependencies: []
