---
- name: Verify Docker Compose plugin is installed
  ansible.builtin.command:
    cmd: docker compose version
  register: docker_compose_version
  changed_when: false

- name: Display Docker Compose version
  ansible.builtin.debug:
    msg: "{{ docker_compose_version.stdout }}"
